name = "fluxly-ccs"
main = "src/cloudflare.ts"
compatibility_date = "2025-06-13"

[env.production.vars]
ALLOWED_ORIGINS = "https://fluxly.app"
CORS_ALLOW_LOCALHOST = "false"
CORS_ENABLE_LOGGING = "false" 